pipeline {
	agent {
		kubernetes {
			inheritFrom 'default'
			defaultContainer 'dind'
			yaml '''
spec:
  containers:
  - name: dind
    image: docker:28-dind
'''
		}
	}

	parameters {
		string(name: 'VERSION', defaultValue: params.VERSION ?: '', description: 'Image version', trim: true)
	}

	environment { 
		APP_NAME = 'jenkins-buildpack'
		GITHUB_URL = 'https://github.com/maxmorhardt/jenkins-jobs'
	}

	stages {
		stage('Git Clone') {
			steps {
				script {
					if ("$VERSION".isEmpty()) {
						currentBuild.result = 'ABORTED'
						error('Version parameter not supplied')
					}

					checkout scmGit(
						branches: [[
							name: "$BRANCH_NAME"
						]],
						userRemoteConfigs: [[
							credentialsId: 'github',
							url: "$GITHUB_URL"
						]]
					)

					sh 'ls -lah'
				}
			}
		}

		stage('CI') {
			steps {
				script {
					withCredentials([usernamePassword(credentialsId: 'docker', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
						sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
						
						sh "docker buildx build --platform linux/arm64/v8 . --tag $DOCKER_USERNAME/$APP_NAME:$VERSION --tag $DOCKER_USERNAME/$APP_NAME:latest --file buildpack/Dockerfile"
						sh "docker push $DOCKER_USERNAME/$APP_NAME --all-tags"
					}
				}
			}
		}
	}
}