pipeline {
	agent {
		kubernetes {
			inheritFrom 'default'
			defaultContainer 'dind'
		}
	}

	parameters {
		string(name: 'VERSION', defaultValue: params.VERSION ?: '', description: 'Image version', trim: true)
	}

	environment { 
		APP_NAME = 'jenkins-buildpack'
		GITHUB_URL = 'https://github.com/maxmorhardt/jenkins-jobs'
	}

	stages {
		stage('Git Clone') {
			steps {
				script {
					checkout scmGit(
						branches: [[
							name: "$BRANCH_NAME"
						]],
						userRemoteConfigs: [[
							credentialsId: 'github',
							url: "$GITHUB_URL"
						]]
					)

					sh 'ls -lah'
					echo "Version: $VERSION"
				}
			}
		}

		stage('CI') {
			steps {
				script {
					withCredentials([usernamePassword(credentialsId: 'docker', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
						sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
						
						sh "docker buildx build --platform linux/arm64/v8 . --tag $DOCKER_USERNAME/$APP_NAME:$VERSION --tag $DOCKER_USERNAME/$APP_NAME:latest --file buildpack/Dockerfile"
						sh "docker push $DOCKER_USERNAME/$APP_NAME --all-tags"
					}
				}
			}
		}
	}
}