pipeline {
	agent {
		kubernetes {
			inheritFrom 'default'
			defaultContainer 'buildpack'
		}
	}

	options {
		timeout(time: 5, unit: 'MINUTES')
		buildDiscarder(logRotator(numToKeepStr: '5'))
	}

	parameters {
		string(name: 'GITHUB_URL', defaultValue: params.GITHUB_URL ?: '', description: 'GitHub URL', trim: true)
		string(name: 'BRANCH', defaultValue: params.BRANCH ?: '', description: 'GitHub branch', trim: true)
		string(name: 'MANIFEST_FILE_PATH', defaultValue: params.MANIFEST_FILE_PATH ?: '', description: 'Path to manifest file', trim: true)
		string(name: 'NAMESPACE', defaultValue: params.NAMESPACE ?: '', description: 'Namespace for manifest', trim: true)
	}

	stages {
		stage('Setup') {
			steps {
				script {
					withCredentials([file(credentialsId: 'kube-config', variable: 'KUBE_CONFIG')]) {
						checkout scmGit(
							branches: [[
								name: "$BRANCH"
							]],
							userRemoteConfigs: [[
								credentialsId: 'github',
								url: "$GITHUB_URL"
							]]
						)

						sh 'mkdir -p $WORKSPACE/.kube && cp $KUBE_CONFIG $WORKSPACE/.kube/config'
						sh 'ls -lah'

						echo "GITHUB_URL: $GITHUB_URL"
						echo "BRANCH: $BRANCH"
						echo "MANIFEST_FILE_PATH: $MANIFEST_FILE_PATH"
						echo "NAMESPACE: $NAMESPACE"
					}
				}
			}
		}

		stage('Apply Manifest') {
			steps {
				script {
					sh "kubectl apply -f $MANIFEST_FILE_PATH -n $NAMESPACE"
				}
			}
		}
	}
}